Done 3.4
estonianec/school pull request #3
Opened 2022-02-21 10:30 UTC by estonianec

Done 3.4

2022-02-22 17:52 UTC, rmuhamedgaliev requested changes
Требуются правки 📝

2022-02-22 17:52 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
> +    public ResponseEntity<Collection<Faculty>> filterByColorAndFindByColorIgnoreCaseOrNameIgnoreCase(@RequestParam(value = "filter-by-color", required = false) String color, @RequestParam(value = "co
Параметры с тире(-) использовать не надо, есть другие знаки похожие на тире в разных системах и будет путанница, старайся в вебе использовать camelCase нотацию в запросах

2022-02-22 17:52 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
>      @DeleteMapping("{id}")
Для референса пример 

```
@RestController
@RequestMapping("faculty")
public class FacultyController {

    private final FacultyService facultyService;

    public FacultyController(FacultyService facultyService) {
        this.facultyService = facultyService;
    }

    @PostMapping
    public Faculty createFaculty(@RequestBody Faculty faculty) {
        return facultyService.createFaculty(faculty);
    }

    @GetMapping("{id}")
    public ResponseEntity<Faculty> getFaculty(@PathVariable long id) {
        Faculty faculty = facultyService.getFaculty(id);
        if (faculty == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }
        return ResponseEntity.ok(faculty);
    }

    @GetMapping(params = {"color"})
    public ResponseEntity<Collection<Faculty>> getFacultyByColor(@RequestParam(value = "color", required = false) String color) {
        Collection<Faculty> facultyByColor = facultyService.getFacultyByColor(color);
        if (facultyByColor.size() == 0) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }
        return ResponseEntity.ok(facultyByColor);
    }

    @GetMapping(params = {"color", "name"})
    public ResponseEntity<Collection<Faculty>> getFacultyByColorOrName(@RequestParam(value = "color", required = false) String color,
                                                                       @RequestParam(value = "name", required = false) String name) {
        Collection<Faculty> facultyByColorOrName = facultyService.getFacultyByColorOrName(color, name);
        if (facultyByColorOrName.size() == 0) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }
        return ResponseEntity.ok(facultyByColorOrName);
    }

    @PutMapping
    public ResponseEntity<Faculty> updateFaculty(@RequestBody Faculty faculty) {
        Faculty facultyForUpdate = facultyService.updateFaculty(faculty);
        if (facultyForUpdate == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }
        return ResponseEntity.ok(facultyForUpdate);
    }

    @DeleteMapping("{id}")
    public ResponseEntity<Faculty> deleteFaculty(@PathVariable long id) {
        facultyService.deleteFaculty(id);
        return ResponseEntity.ok().build();
    }
}
```

2022-02-22 17:52 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/controller/StudentController.java
>  @RestController
```
@RestController
@RequestMapping("student")
public class StudentController {

    private final StudentService studentService;

    public StudentController(StudentService studentService) {
        this.studentService = studentService;
    }

    @PostMapping
    public Student createFaculty(@RequestBody Student student) {
        return studentService.createStudent(student);
    }

    @GetMapping("{id}")
    public ResponseEntity<Student> getFaculty(@PathVariable long id) {
        Student student = studentService.getStudent(id);
        if (student == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }
        return ResponseEntity.ok(student);
    }

    @GetMapping(params = {"age"})
    public ResponseEntity<Collection<Student>> getStudensByAge(@RequestParam(value = "age", required = false) int age) {
        Collection<Student> studensByAge = studentService.getStudensByAge(age);
        if (studensByAge.size() == 0) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }
        return ResponseEntity.ok(studensByAge);
    }

    @GetMapping(params = {"ageMin", "ageMax"})
    public ResponseEntity<Collection<Student>> getStudensByAgeRange(@RequestParam(value = "ageMin", required = false) int ageMin,
                                                                    @RequestParam(value = "ageMax", required = false) int ageMax) {
        Collection<Student> studensByAgeRange = studentService.getStudensByAgeRange(ageMin, ageMax);
        if (studensByAgeRange.size() == 0) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }
        return ResponseEntity.ok(studensByAgeRange);
    }

    @PutMapping
    public ResponseEntity<Student> updateFaculty(@RequestBody Student student) {
        Student studentForUpdate = studentService.updateStudent(student);
        if (studentForUpdate == null) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }
        return ResponseEntity.ok(studentForUpdate);
    }

    @DeleteMapping("{id}")
    public ResponseEntity<Student> deleteFaculty(@PathVariable long id) {
        studentService.deleteStudent(id);
        return ResponseEntity.ok().build();
    }
}
```

2022-02-22 17:52 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/repository/StudentRepository.java
> +    Collection<Student> findByAgeBetween(int min, int max);
лучше и писать minAge, maxAge

2022-02-22 17:52 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/scripts.sql
> +WHERE age > 2
Можно еще писать between - https://www.postgresqltutorial.com/postgresql-between/

2022-02-22 17:52 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/service/impl/StudentServiceImpl.java
>                  .filter(e -> e.getAge() == age)
Брать все и фильтровать по возрасту не очень, лучше сразу в базе искать. Иначе если миллиард записей и все в память ложить, то сервер упасть может

2022-02-22 19:09 UTC, estonianec commented on src/main/java/ru/hogwarts/school/repository/StudentRepository.java
> +    Collection<Student> findByAgeBetween(int min, int max);
В ДЗ переменные требуется называть min и max.

2022-02-22 19:09 UTC, estonianec commented on src/main/java/ru/hogwarts/school/scripts.sql
> +WHERE age > 2
Можно. Спасибо. Буду пользоваться.

2022-02-22 19:09 UTC, estonianec commented on src/main/java/ru/hogwarts/school/service/impl/StudentServiceImpl.java
>                  .filter(e -> e.getAge() == age)
Когда мы писали этот метод мы ещё не проходили кастомные запросы к БД. В ДЗ не было требования переписать этот метод с учётом новых знаний.

2022-02-22 19:09 UTC, estonianec commented on src/main/java/ru/hogwarts/school/controller/StudentController.java
>  @RestController
Почему метод на создание студента называется createFaculty, а на получение студента getFaculty? Чем мой код принципиально отличается от представленного в примере?

2022-02-22 19:10 UTC, estonianec commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
>      @DeleteMapping("{id}")
А мой вариант нерабочий? Чем он хуже варианта с перегрузкой метода в контроллере? А что если в вашем референсе передать только name, то выдаёт статус 400? Почему вдруг color стал обязательным?

2022-02-22 19:10 UTC, estonianec commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
> +    public ResponseEntity<Collection<Faculty>> filterByColorAndFindByColorIgnoreCaseOrNameIgnoreCase(@RequestParam(value = "filter-by-color", required = false) String color, @RequestParam(value = "co
Статьи из гугла предлагают использовать именно kebab-case в url, в именах директорий, в именах свойств JSON, в именах атрибутов HTML.
До этого ДЗ то не было ошибкой и даже ни разу не обсуждалось.

2022-02-22 20:16 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/controller/FacultyController.java
> +    public ResponseEntity<Collection<Faculty>> filterByColorAndFindByColorIgnoreCaseOrNameIgnoreCase(@RequestParam(value = "filter-by-color", required = false) String color, @RequestParam(value = "co
поверь пожалуйста опыту моему, я тот человек который настрадался. kebab-case тут не подходит

2022-02-23 09:15 UTC, rmuhamedgaliev approved these changes
Проведена, большая работа! Принято! 🏆

2022-02-23 09:17 UTC, rmuhamedgaliev commented
Можно мержить.

2022-02-23 10:05 UTC, merged